import Header from "./components/Header/Header"
import "./globals.css"

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
}

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className="vsc-initialized">
				<Header />

				{children}
			</body>
		</html>
	)
}
